#!/usr/bin/env bash
# ralph/config.sh — the packaged DEFAULTS for every knob ralph reads.
#
# Do NOT edit this file to wire up a project: it belongs to the install and an
# update overwrites it. Run `ralph init` and edit the project's .ralph/config.sh
# instead. lib.sh sources that file FIRST and this one second, so the project
# only writes what it wants to change and a knob added upstream still gets a
# default. Env wins over both — every value uses the ${VAR:-default} idiom, and
# every array is only defaulted when the project left it undeclared.
#
# Sourced by lib.sh (all entry points) and status.sh; keep it side-effect free.
#
# Ralph is language and framework agnostic. It knows how to drive GitHub, git and
# claude; it knows nothing about your toolchain. Everything toolchain-shaped is a
# command string or a directory list below. Per-language recipes live in the
# starter that `ralph init` writes.

# GitHub triage labels (Matt Pocock vocabulary). Must exist on the repo.
READY_LABEL="${READY_LABEL:-ready-for-agent}"   # the queue: issues the AFK agent may pick up
WORKING_LABEL="${WORKING_LABEL:-claude-working}" # transient "in progress" marker
HUMAN_LABEL="${HUMAN_LABEL:-ready-for-human}"    # handback: issues a human must handle

# Branch PRs target and merge into.
BASE_BRANCH="${BASE_BRANCH:-main}"

# --- Objective quality gate --------------------------------------------------
# The orchestrator (never the agent) runs these in the worktree, so approval does
# not depend on an agent's honest "tests pass" claim.
#
# TEST_DIR is the dir the gate runs in, relative to the repo root. LINT_CMD and
# TEST_CMD also appear verbatim in the agent prompts, so keep them copy-pasteable
# shell commands. An EMPTY command is SKIPPED — by the gate and by the prompts
# alike — so a project with no linter just leaves LINT_CMD empty.
#
# Leaving BOTH empty makes the gate a no-op. Ralph logs a warning every cycle in
# that case rather than reporting a pass it never checked.
TEST_DIR="${TEST_DIR:-.}"
LINT_CMD="${LINT_CMD:-}"
TEST_CMD="${TEST_CMD:-}"

# Dependency install, run in TEST_DIR before LINT_CMD and TEST_CMD. Empty = the
# project needs no install step.
#
# SETUP_MARKER is the directory SETUP_CMD populates. When it is missing or EMPTY,
# the install re-runs. The empty case is load-bearing: the sandbox bind-mounts
# that directory, and docker leaves an empty root-owned mountpoint behind on
# container exit — without the check the host gate would run with no toolchain
# installed and could never pass. SETUP_LOCK re-runs the install when the
# lockfile is newer than the marker.
#
# Leave SETUP_MARKER empty to run SETUP_CMD every cycle. That is right for a
# toolchain whose install is already a cheap no-op when warm (`go mod download`,
# `cargo fetch`), and wrong for one that is not (`npm ci`).
SETUP_CMD="${SETUP_CMD:-}"
SETUP_MARKER="${SETUP_MARKER:-}"
SETUP_LOCK="${SETUP_LOCK:-}"

# Advisory dependency audit, run in TEST_DIR when RALPH_AUDIT=1. Logged, never
# blocks a PR. Empty = no audit is wired up for this stack.
AUDIT_CMD="${AUDIT_CMD:-}"

# --- Sandbox -----------------------------------------------------------------
# Docker image tag for the writer sandbox, built by `ralph sandbox-build`. The
# Dockerfile takes a BASE_IMAGE build arg, so one Dockerfile serves every
# toolchain — see sandbox/Dockerfile in the install.
RALPH_SANDBOX_IMAGE="${RALPH_SANDBOX_IMAGE:-ralph-impl}"

# Base image the sandbox is built FROM — the one place the project's toolchain
# enters the container. `ralph sandbox-build` passes it as the BASE_IMAGE build
# arg, so one Dockerfile serves every language.
RALPH_SANDBOX_BASE="${RALPH_SANDBOX_BASE:-debian:bookworm-slim}"

# In-repo dependency caches bind-mounted from the repo root into the sandbox
# worktree, so the offline-of-GitHub agent can lint and test without
# re-downloading. Every WORKSPACE_DIR x DEP_DIR pair that exists on the host is
# mounted at the same relative path inside the worktree; missing pairs are
# skipped. List every workspace package the gate touches.
if ! declare -p RALPH_WORKSPACE_DIRS >/dev/null 2>&1; then
  RALPH_WORKSPACE_DIRS=(".")
  if [ "$TEST_DIR" != "." ]; then RALPH_WORKSPACE_DIRS+=("$TEST_DIR"); fi
fi
declare -p RALPH_DEP_DIRS >/dev/null 2>&1 || RALPH_DEP_DIRS=()

# Toolchain caches that live outside the repo, in the container's $HOME. That
# HOME is empty and thrown away on exit, so without these every run re-downloads
# the world. Each entry is one docker -v spec. Use a NAMED VOLUME, not a host
# path: a host path would hand the sandboxed agent a writable directory on your
# machine, which is the thing the sandbox exists to prevent.
declare -p RALPH_CACHE_MOUNTS >/dev/null 2>&1 || RALPH_CACHE_MOUNTS=()

# Per-language recipes (npm, pnpm, Go, Rust, Python, Ruby, JVM) are in the
# starter file `ralph init` writes to .ralph/config.sh, next to the values you
# actually edit. `ralph init --print` prints it without writing.
